### ISSUE TITLE
Forking Your Repository

### ISSUE THREAD

**Issue by muzashiyukihimecoding** [Arizab02/mini-project#2]
Assalamu'alaikum warahmatullahi wabarakaatuh

Hi, Good Afternoon, my friend.

I'm Rasyid Nabil Pujantara, or Muzashi Yukihime, it's my code name.
I've just forked your mini-project Repository for being my code reference. Don't worry, ain't copy your code all about, but it's just for my reference. You can also see my code, or my reps if you want.

By the way, I had some codes from my bootcamp. I've not continued it but maybe there was some important codes, and some "expensive knowledge" that I got :v. I still learn these codes and look for another shorts code to easy coding projects.

Ok, overall thanks for you, and let's learn these together :))

See you again.
Wasalamu'alaikum warahmatullahi wabarakaatuh

**Comment by Arizab02** [comment]
Wa'alaikumussalam wa rahmatullah wa barakatuh...

**Comment by Arizab02** [comment]
و عليكم السلام و رحمة الله و بركاته.... 

صياح الخير و أهلا بك..

 يا إخا لا بأس به لو أنك تحمل كل هذا الكود المصدري لهذا البرنامج والموقع, و تجعله ملكا لك بعدما تحرفه. و انا ايضا أدرسه الان... فحيا بنا ندرس معا كي ننجح و إياك بالتحميل و لا تحريف... لانه لا يؤثرك و لا يمهرك.

فاﻵخر شكرت لك شكرا علي حثك لي و لمن يقرأ ذه الكتابة.
